// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash, display_name)
VALUES ($1, $2, $3, $4)
RETURNING id, username, email, display_name, avatar_url, push_token, created_at, updated_at
`

type CreateUserParams struct {
	Username     string `db:"username" json:"username"`
	Email        string `db:"email" json:"email"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
	DisplayName  string `db:"display_name" json:"display_name"`
}

type CreateUserRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Username    string             `db:"username" json:"username"`
	Email       string             `db:"email" json:"email"`
	DisplayName string             `db:"display_name" json:"display_name"`
	AvatarUrl   pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	PushToken   pgtype.Text        `db:"push_token" json:"push_token"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.PushToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, display_name, avatar_url, push_token, created_at, updated_at
FROM users
WHERE LOWER(email) = LOWER($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.PushToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, display_name, avatar_url, push_token, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Username    string             `db:"username" json:"username"`
	Email       string             `db:"email" json:"email"`
	DisplayName string             `db:"display_name" json:"display_name"`
	AvatarUrl   pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	PushToken   pgtype.Text        `db:"push_token" json:"push_token"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.PushToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, display_name, avatar_url, push_token, created_at, updated_at
FROM users
WHERE LOWER(username) = LOWER($1)
`

type GetUserByUsernameRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Username    string             `db:"username" json:"username"`
	Email       string             `db:"email" json:"email"`
	DisplayName string             `db:"display_name" json:"display_name"`
	AvatarUrl   pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	PushToken   pgtype.Text        `db:"push_token" json:"push_token"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, lower string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, lower)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.PushToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET display_name = COALESCE($2, display_name),
    avatar_url = COALESCE($3, avatar_url),
    push_token = COALESCE($4, push_token),
    updated_at = NOW()
WHERE id = $1
RETURNING id, username, email, display_name, avatar_url, push_token, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	DisplayName string      `db:"display_name" json:"display_name"`
	AvatarUrl   pgtype.Text `db:"avatar_url" json:"avatar_url"`
	PushToken   pgtype.Text `db:"push_token" json:"push_token"`
}

type UpdateUserProfileRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Username    string             `db:"username" json:"username"`
	Email       string             `db:"email" json:"email"`
	DisplayName string             `db:"display_name" json:"display_name"`
	AvatarUrl   pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	PushToken   pgtype.Text        `db:"push_token" json:"push_token"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.PushToken,
	)
	var i UpdateUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.PushToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPushToken = `-- name: UpdateUserPushToken :exec
UPDATE users
SET push_token = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserPushTokenParams struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	PushToken pgtype.Text `db:"push_token" json:"push_token"`
}

func (q *Queries) UpdateUserPushToken(ctx context.Context, arg UpdateUserPushTokenParams) error {
	_, err := q.db.Exec(ctx, updateUserPushToken, arg.ID, arg.PushToken)
	return err
}
