// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForInsertLeaderboardEntriesBulk implements pgx.CopyFromSource.
type iteratorForInsertLeaderboardEntriesBulk struct {
	rows                 []InsertLeaderboardEntriesBulkParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertLeaderboardEntriesBulk) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertLeaderboardEntriesBulk) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].UserID,
		r.rows[0].VehicleType,
		r.rows[0].PeriodType,
		r.rows[0].PeriodStart,
		r.rows[0].TotalKm,
		r.rows[0].TotalRides,
		r.rows[0].Rank,
	}, nil
}

func (r iteratorForInsertLeaderboardEntriesBulk) Err() error {
	return nil
}

func (q *Queries) InsertLeaderboardEntriesBulk(ctx context.Context, arg []InsertLeaderboardEntriesBulkParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"leaderboard_entries"}, []string{"user_id", "vehicle_type", "period_type", "period_start", "total_km", "total_rides", "rank"}, &iteratorForInsertLeaderboardEntriesBulk{rows: arg})
}
