// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: leaderboard.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const computeAllTimeRankings = `-- name: ComputeAllTimeRankings :many
SELECT
    r.user_id,
    SUM(r.distance_km)::FLOAT8 as total_km,
    COUNT(DISTINCT r.id) as total_rides
FROM rides r
WHERE r.status = 'completed'
GROUP BY r.user_id
ORDER BY total_km DESC, total_rides DESC
`

type ComputeAllTimeRankingsRow struct {
	UserID     pgtype.UUID `db:"user_id" json:"user_id"`
	TotalKm    float64     `db:"total_km" json:"total_km"`
	TotalRides int64       `db:"total_rides" json:"total_rides"`
}

func (q *Queries) ComputeAllTimeRankings(ctx context.Context) ([]ComputeAllTimeRankingsRow, error) {
	rows, err := q.db.Query(ctx, computeAllTimeRankings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComputeAllTimeRankingsRow{}
	for rows.Next() {
		var i ComputeAllTimeRankingsRow
		if err := rows.Scan(&i.UserID, &i.TotalKm, &i.TotalRides); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const computeAllTimeRankingsByVehicle = `-- name: ComputeAllTimeRankingsByVehicle :many
SELECT
    r.user_id,
    v.type as vehicle_type,
    SUM(r.distance_km)::FLOAT8 as total_km,
    COUNT(DISTINCT r.id) as total_rides
FROM rides r
JOIN vehicles v ON r.vehicle_id = v.id
WHERE r.status = 'completed'
  AND v.type = $1
GROUP BY r.user_id, v.type
ORDER BY total_km DESC, total_rides DESC
`

type ComputeAllTimeRankingsByVehicleRow struct {
	UserID      pgtype.UUID `db:"user_id" json:"user_id"`
	VehicleType VehicleType `db:"vehicle_type" json:"vehicle_type"`
	TotalKm     float64     `db:"total_km" json:"total_km"`
	TotalRides  int64       `db:"total_rides" json:"total_rides"`
}

func (q *Queries) ComputeAllTimeRankingsByVehicle(ctx context.Context, type_ VehicleType) ([]ComputeAllTimeRankingsByVehicleRow, error) {
	rows, err := q.db.Query(ctx, computeAllTimeRankingsByVehicle, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComputeAllTimeRankingsByVehicleRow{}
	for rows.Next() {
		var i ComputeAllTimeRankingsByVehicleRow
		if err := rows.Scan(
			&i.UserID,
			&i.VehicleType,
			&i.TotalKm,
			&i.TotalRides,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const computeMonthlyRankings = `-- name: ComputeMonthlyRankings :many
SELECT
    r.user_id,
    SUM(r.distance_km)::FLOAT8 as total_km,
    COUNT(DISTINCT r.id) as total_rides
FROM rides r
WHERE r.status = 'completed'
  AND r.started_at >= $1 AND r.started_at < $1 + INTERVAL '1 month'
GROUP BY r.user_id
ORDER BY total_km DESC, total_rides DESC
`

type ComputeMonthlyRankingsRow struct {
	UserID     pgtype.UUID `db:"user_id" json:"user_id"`
	TotalKm    float64     `db:"total_km" json:"total_km"`
	TotalRides int64       `db:"total_rides" json:"total_rides"`
}

func (q *Queries) ComputeMonthlyRankings(ctx context.Context, startedAt pgtype.Timestamptz) ([]ComputeMonthlyRankingsRow, error) {
	rows, err := q.db.Query(ctx, computeMonthlyRankings, startedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComputeMonthlyRankingsRow{}
	for rows.Next() {
		var i ComputeMonthlyRankingsRow
		if err := rows.Scan(&i.UserID, &i.TotalKm, &i.TotalRides); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const computeMonthlyRankingsByVehicle = `-- name: ComputeMonthlyRankingsByVehicle :many
SELECT
    r.user_id,
    v.type as vehicle_type,
    SUM(r.distance_km)::FLOAT8 as total_km,
    COUNT(DISTINCT r.id) as total_rides
FROM rides r
JOIN vehicles v ON r.vehicle_id = v.id
WHERE r.status = 'completed'
  AND v.type = $2
  AND r.started_at >= $1 AND r.started_at < $1 + INTERVAL '1 month'
GROUP BY r.user_id, v.type
ORDER BY total_km DESC, total_rides DESC
`

type ComputeMonthlyRankingsByVehicleParams struct {
	StartedAt pgtype.Timestamptz `db:"started_at" json:"started_at"`
	Type      VehicleType        `db:"type" json:"type"`
}

type ComputeMonthlyRankingsByVehicleRow struct {
	UserID      pgtype.UUID `db:"user_id" json:"user_id"`
	VehicleType VehicleType `db:"vehicle_type" json:"vehicle_type"`
	TotalKm     float64     `db:"total_km" json:"total_km"`
	TotalRides  int64       `db:"total_rides" json:"total_rides"`
}

func (q *Queries) ComputeMonthlyRankingsByVehicle(ctx context.Context, arg ComputeMonthlyRankingsByVehicleParams) ([]ComputeMonthlyRankingsByVehicleRow, error) {
	rows, err := q.db.Query(ctx, computeMonthlyRankingsByVehicle, arg.StartedAt, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComputeMonthlyRankingsByVehicleRow{}
	for rows.Next() {
		var i ComputeMonthlyRankingsByVehicleRow
		if err := rows.Scan(
			&i.UserID,
			&i.VehicleType,
			&i.TotalKm,
			&i.TotalRides,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const computeWeeklyRankings = `-- name: ComputeWeeklyRankings :many

SELECT
    r.user_id,
    SUM(r.distance_km)::FLOAT8 as total_km,
    COUNT(DISTINCT r.id) as total_rides
FROM rides r
WHERE r.status = 'completed'
  AND r.started_at >= $1 AND r.started_at < $1 + INTERVAL '7 days'
GROUP BY r.user_id
ORDER BY total_km DESC, total_rides DESC
`

type ComputeWeeklyRankingsRow struct {
	UserID     pgtype.UUID `db:"user_id" json:"user_id"`
	TotalKm    float64     `db:"total_km" json:"total_km"`
	TotalRides int64       `db:"total_rides" json:"total_rides"`
}

// Compute rankings for current period (used by cron job)
// Optimized to scan rides table instead of users table for O(active_rides) performance
// Explicit ::FLOAT8 cast on SUM() to prevent sqlc type inference bugs
func (q *Queries) ComputeWeeklyRankings(ctx context.Context, startedAt pgtype.Timestamptz) ([]ComputeWeeklyRankingsRow, error) {
	rows, err := q.db.Query(ctx, computeWeeklyRankings, startedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComputeWeeklyRankingsRow{}
	for rows.Next() {
		var i ComputeWeeklyRankingsRow
		if err := rows.Scan(&i.UserID, &i.TotalKm, &i.TotalRides); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const computeWeeklyRankingsByVehicle = `-- name: ComputeWeeklyRankingsByVehicle :many
SELECT
    r.user_id,
    v.type as vehicle_type,
    SUM(r.distance_km)::FLOAT8 as total_km,
    COUNT(DISTINCT r.id) as total_rides
FROM rides r
JOIN vehicles v ON r.vehicle_id = v.id
WHERE r.status = 'completed'
  AND v.type = $2
  AND r.started_at >= $1 AND r.started_at < $1 + INTERVAL '7 days'
GROUP BY r.user_id, v.type
ORDER BY total_km DESC, total_rides DESC
`

type ComputeWeeklyRankingsByVehicleParams struct {
	StartedAt pgtype.Timestamptz `db:"started_at" json:"started_at"`
	Type      VehicleType        `db:"type" json:"type"`
}

type ComputeWeeklyRankingsByVehicleRow struct {
	UserID      pgtype.UUID `db:"user_id" json:"user_id"`
	VehicleType VehicleType `db:"vehicle_type" json:"vehicle_type"`
	TotalKm     float64     `db:"total_km" json:"total_km"`
	TotalRides  int64       `db:"total_rides" json:"total_rides"`
}

func (q *Queries) ComputeWeeklyRankingsByVehicle(ctx context.Context, arg ComputeWeeklyRankingsByVehicleParams) ([]ComputeWeeklyRankingsByVehicleRow, error) {
	rows, err := q.db.Query(ctx, computeWeeklyRankingsByVehicle, arg.StartedAt, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComputeWeeklyRankingsByVehicleRow{}
	for rows.Next() {
		var i ComputeWeeklyRankingsByVehicleRow
		if err := rows.Scan(
			&i.UserID,
			&i.VehicleType,
			&i.TotalKm,
			&i.TotalRides,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteLeaderboardEntries = `-- name: DeleteLeaderboardEntries :exec
DELETE FROM leaderboard_entries
WHERE period_type = $1 AND period_start = $2
  AND (vehicle_type IS NULL OR vehicle_type = $3)
`

type DeleteLeaderboardEntriesParams struct {
	PeriodType  string          `db:"period_type" json:"period_type"`
	PeriodStart pgtype.Date     `db:"period_start" json:"period_start"`
	VehicleType NullVehicleType `db:"vehicle_type" json:"vehicle_type"`
}

func (q *Queries) DeleteLeaderboardEntries(ctx context.Context, arg DeleteLeaderboardEntriesParams) error {
	_, err := q.db.Exec(ctx, deleteLeaderboardEntries, arg.PeriodType, arg.PeriodStart, arg.VehicleType)
	return err
}

const deleteLeaderboardPeriod = `-- name: DeleteLeaderboardPeriod :exec
DELETE FROM leaderboard_entries
WHERE period_type = $1 AND period_start = $2
`

type DeleteLeaderboardPeriodParams struct {
	PeriodType  string      `db:"period_type" json:"period_type"`
	PeriodStart pgtype.Date `db:"period_start" json:"period_start"`
}

func (q *Queries) DeleteLeaderboardPeriod(ctx context.Context, arg DeleteLeaderboardPeriodParams) error {
	_, err := q.db.Exec(ctx, deleteLeaderboardPeriod, arg.PeriodType, arg.PeriodStart)
	return err
}

const getFriendsLeaderboard = `-- name: GetFriendsLeaderboard :many
SELECT l.id, l.user_id, l.vehicle_type, l.period_type, l.period_start, l.total_km, l.total_rides, l.rank, l.created_at, l.updated_at
FROM leaderboard_entries l
JOIN follows f ON l.user_id = f.following_id
WHERE f.follower_id = $1 AND l.period_type = $2 AND l.period_start = $3
ORDER BY l.rank ASC
LIMIT $4 OFFSET $5
`

type GetFriendsLeaderboardParams struct {
	FollowerID  pgtype.UUID `db:"follower_id" json:"follower_id"`
	PeriodType  string      `db:"period_type" json:"period_type"`
	PeriodStart pgtype.Date `db:"period_start" json:"period_start"`
	Limit       int32       `db:"limit" json:"limit"`
	Offset      int32       `db:"offset" json:"offset"`
}

func (q *Queries) GetFriendsLeaderboard(ctx context.Context, arg GetFriendsLeaderboardParams) ([]LeaderboardEntry, error) {
	rows, err := q.db.Query(ctx, getFriendsLeaderboard,
		arg.FollowerID,
		arg.PeriodType,
		arg.PeriodStart,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeaderboardEntry{}
	for rows.Next() {
		var i LeaderboardEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VehicleType,
			&i.PeriodType,
			&i.PeriodStart,
			&i.TotalKm,
			&i.TotalRides,
			&i.Rank,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFriendsLeaderboardByVehicle = `-- name: GetFriendsLeaderboardByVehicle :many
SELECT l.id, l.user_id, l.vehicle_type, l.period_type, l.period_start, l.total_km, l.total_rides, l.rank, l.created_at, l.updated_at
FROM leaderboard_entries l
JOIN follows f ON l.user_id = f.following_id
WHERE f.follower_id = $1 AND l.period_type = $2 AND l.period_start = $3 AND l.vehicle_type = $4
ORDER BY l.rank ASC
LIMIT $5 OFFSET $6
`

type GetFriendsLeaderboardByVehicleParams struct {
	FollowerID  pgtype.UUID     `db:"follower_id" json:"follower_id"`
	PeriodType  string          `db:"period_type" json:"period_type"`
	PeriodStart pgtype.Date     `db:"period_start" json:"period_start"`
	VehicleType NullVehicleType `db:"vehicle_type" json:"vehicle_type"`
	Limit       int32           `db:"limit" json:"limit"`
	Offset      int32           `db:"offset" json:"offset"`
}

func (q *Queries) GetFriendsLeaderboardByVehicle(ctx context.Context, arg GetFriendsLeaderboardByVehicleParams) ([]LeaderboardEntry, error) {
	rows, err := q.db.Query(ctx, getFriendsLeaderboardByVehicle,
		arg.FollowerID,
		arg.PeriodType,
		arg.PeriodStart,
		arg.VehicleType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeaderboardEntry{}
	for rows.Next() {
		var i LeaderboardEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VehicleType,
			&i.PeriodType,
			&i.PeriodStart,
			&i.TotalKm,
			&i.TotalRides,
			&i.Rank,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLeaderboardByPeriod = `-- name: GetLeaderboardByPeriod :many
SELECT id, user_id, vehicle_type, period_type, period_start, total_km, total_rides, rank, created_at, updated_at
FROM leaderboard_entries
WHERE period_type = $1 AND period_start = $2
ORDER BY rank ASC
LIMIT $3 OFFSET $4
`

type GetLeaderboardByPeriodParams struct {
	PeriodType  string      `db:"period_type" json:"period_type"`
	PeriodStart pgtype.Date `db:"period_start" json:"period_start"`
	Limit       int32       `db:"limit" json:"limit"`
	Offset      int32       `db:"offset" json:"offset"`
}

func (q *Queries) GetLeaderboardByPeriod(ctx context.Context, arg GetLeaderboardByPeriodParams) ([]LeaderboardEntry, error) {
	rows, err := q.db.Query(ctx, getLeaderboardByPeriod,
		arg.PeriodType,
		arg.PeriodStart,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeaderboardEntry{}
	for rows.Next() {
		var i LeaderboardEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VehicleType,
			&i.PeriodType,
			&i.PeriodStart,
			&i.TotalKm,
			&i.TotalRides,
			&i.Rank,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLeaderboardByPeriodAndVehicle = `-- name: GetLeaderboardByPeriodAndVehicle :many
SELECT id, user_id, vehicle_type, period_type, period_start, total_km, total_rides, rank, created_at, updated_at
FROM leaderboard_entries
WHERE period_type = $1 AND period_start = $2 AND vehicle_type = $3
ORDER BY rank ASC
LIMIT $4 OFFSET $5
`

type GetLeaderboardByPeriodAndVehicleParams struct {
	PeriodType  string          `db:"period_type" json:"period_type"`
	PeriodStart pgtype.Date     `db:"period_start" json:"period_start"`
	VehicleType NullVehicleType `db:"vehicle_type" json:"vehicle_type"`
	Limit       int32           `db:"limit" json:"limit"`
	Offset      int32           `db:"offset" json:"offset"`
}

func (q *Queries) GetLeaderboardByPeriodAndVehicle(ctx context.Context, arg GetLeaderboardByPeriodAndVehicleParams) ([]LeaderboardEntry, error) {
	rows, err := q.db.Query(ctx, getLeaderboardByPeriodAndVehicle,
		arg.PeriodType,
		arg.PeriodStart,
		arg.VehicleType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeaderboardEntry{}
	for rows.Next() {
		var i LeaderboardEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VehicleType,
			&i.PeriodType,
			&i.PeriodStart,
			&i.TotalKm,
			&i.TotalRides,
			&i.Rank,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLeaderboardEntryByRank = `-- name: GetLeaderboardEntryByRank :one
SELECT id, user_id, vehicle_type, period_type, period_start, total_km, total_rides, rank, created_at, updated_at
FROM leaderboard_entries
WHERE period_type = $1 AND period_start = $2 AND rank = $3
`

type GetLeaderboardEntryByRankParams struct {
	PeriodType  string      `db:"period_type" json:"period_type"`
	PeriodStart pgtype.Date `db:"period_start" json:"period_start"`
	Rank        int32       `db:"rank" json:"rank"`
}

func (q *Queries) GetLeaderboardEntryByRank(ctx context.Context, arg GetLeaderboardEntryByRankParams) (LeaderboardEntry, error) {
	row := q.db.QueryRow(ctx, getLeaderboardEntryByRank, arg.PeriodType, arg.PeriodStart, arg.Rank)
	var i LeaderboardEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VehicleType,
		&i.PeriodType,
		&i.PeriodStart,
		&i.TotalKm,
		&i.TotalRides,
		&i.Rank,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLeaderboardStats = `-- name: GetLeaderboardStats :one
SELECT
    COUNT(DISTINCT user_id) as unique_users,
    COALESCE(SUM(total_km), 0) as total_platform_km,
    COALESCE(SUM(total_rides), 0) as total_platform_rides,
    COALESCE(MAX(rank), 0) as max_rank
FROM leaderboard_entries
WHERE period_type = $1 AND period_start = $2
`

type GetLeaderboardStatsParams struct {
	PeriodType  string      `db:"period_type" json:"period_type"`
	PeriodStart pgtype.Date `db:"period_start" json:"period_start"`
}

type GetLeaderboardStatsRow struct {
	UniqueUsers        int64       `db:"unique_users" json:"unique_users"`
	TotalPlatformKm    interface{} `db:"total_platform_km" json:"total_platform_km"`
	TotalPlatformRides interface{} `db:"total_platform_rides" json:"total_platform_rides"`
	MaxRank            interface{} `db:"max_rank" json:"max_rank"`
}

func (q *Queries) GetLeaderboardStats(ctx context.Context, arg GetLeaderboardStatsParams) (GetLeaderboardStatsRow, error) {
	row := q.db.QueryRow(ctx, getLeaderboardStats, arg.PeriodType, arg.PeriodStart)
	var i GetLeaderboardStatsRow
	err := row.Scan(
		&i.UniqueUsers,
		&i.TotalPlatformKm,
		&i.TotalPlatformRides,
		&i.MaxRank,
	)
	return i, err
}

const getUserLeaderboardRank = `-- name: GetUserLeaderboardRank :one
SELECT id, user_id, vehicle_type, period_type, period_start, total_km, total_rides, rank, created_at, updated_at
FROM leaderboard_entries
WHERE period_type = $1 AND period_start = $2 AND user_id = $3 AND (vehicle_type IS NULL OR vehicle_type = $4)
LIMIT 1
`

type GetUserLeaderboardRankParams struct {
	PeriodType  string          `db:"period_type" json:"period_type"`
	PeriodStart pgtype.Date     `db:"period_start" json:"period_start"`
	UserID      pgtype.UUID     `db:"user_id" json:"user_id"`
	VehicleType NullVehicleType `db:"vehicle_type" json:"vehicle_type"`
}

func (q *Queries) GetUserLeaderboardRank(ctx context.Context, arg GetUserLeaderboardRankParams) (LeaderboardEntry, error) {
	row := q.db.QueryRow(ctx, getUserLeaderboardRank,
		arg.PeriodType,
		arg.PeriodStart,
		arg.UserID,
		arg.VehicleType,
	)
	var i LeaderboardEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VehicleType,
		&i.PeriodType,
		&i.PeriodStart,
		&i.TotalKm,
		&i.TotalRides,
		&i.Rank,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserRankingHistory = `-- name: GetUserRankingHistory :many
SELECT id, user_id, vehicle_type, period_type, period_start, total_km, total_rides, rank, created_at, updated_at
FROM leaderboard_entries
WHERE user_id = $1 AND period_type = $2
ORDER BY period_start DESC
LIMIT $3
`

type GetUserRankingHistoryParams struct {
	UserID     pgtype.UUID `db:"user_id" json:"user_id"`
	PeriodType string      `db:"period_type" json:"period_type"`
	Limit      int32       `db:"limit" json:"limit"`
}

func (q *Queries) GetUserRankingHistory(ctx context.Context, arg GetUserRankingHistoryParams) ([]LeaderboardEntry, error) {
	rows, err := q.db.Query(ctx, getUserRankingHistory, arg.UserID, arg.PeriodType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeaderboardEntry{}
	for rows.Next() {
		var i LeaderboardEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VehicleType,
			&i.PeriodType,
			&i.PeriodStart,
			&i.TotalKm,
			&i.TotalRides,
			&i.Rank,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

type InsertLeaderboardEntriesBulkParams struct {
	UserID      pgtype.UUID     `db:"user_id" json:"user_id"`
	VehicleType NullVehicleType `db:"vehicle_type" json:"vehicle_type"`
	PeriodType  string          `db:"period_type" json:"period_type"`
	PeriodStart pgtype.Date     `db:"period_start" json:"period_start"`
	TotalKm     float64         `db:"total_km" json:"total_km"`
	TotalRides  int32           `db:"total_rides" json:"total_rides"`
	Rank        int32           `db:"rank" json:"rank"`
}

const insertLeaderboardEntry = `-- name: InsertLeaderboardEntry :exec
INSERT INTO leaderboard_entries (user_id, vehicle_type, period_type, period_start, total_km, total_rides, rank)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertLeaderboardEntryParams struct {
	UserID      pgtype.UUID     `db:"user_id" json:"user_id"`
	VehicleType NullVehicleType `db:"vehicle_type" json:"vehicle_type"`
	PeriodType  string          `db:"period_type" json:"period_type"`
	PeriodStart pgtype.Date     `db:"period_start" json:"period_start"`
	TotalKm     float64         `db:"total_km" json:"total_km"`
	TotalRides  int32           `db:"total_rides" json:"total_rides"`
	Rank        int32           `db:"rank" json:"rank"`
}

func (q *Queries) InsertLeaderboardEntry(ctx context.Context, arg InsertLeaderboardEntryParams) error {
	_, err := q.db.Exec(ctx, insertLeaderboardEntry,
		arg.UserID,
		arg.VehicleType,
		arg.PeriodType,
		arg.PeriodStart,
		arg.TotalKm,
		arg.TotalRides,
		arg.Rank,
	)
	return err
}
