// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type RideStatus string

const (
	RideStatusActive    RideStatus = "active"
	RideStatusCompleted RideStatus = "completed"
	RideStatusAbandoned RideStatus = "abandoned"
)

func (e *RideStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RideStatus(s)
	case string:
		*e = RideStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RideStatus: %T", src)
	}
	return nil
}

type NullRideStatus struct {
	RideStatus RideStatus `json:"ride_status"`
	Valid      bool       `json:"valid"` // Valid is true if RideStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRideStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RideStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RideStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRideStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RideStatus), nil
}

type VehicleType string

const (
	VehicleTypeMotor  VehicleType = "motor"
	VehicleTypeMobil  VehicleType = "mobil"
	VehicleTypeSepeda VehicleType = "sepeda"
)

func (e *VehicleType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VehicleType(s)
	case string:
		*e = VehicleType(s)
	default:
		return fmt.Errorf("unsupported scan type for VehicleType: %T", src)
	}
	return nil
}

type NullVehicleType struct {
	VehicleType VehicleType `json:"vehicle_type"`
	Valid       bool        `json:"valid"` // Valid is true if VehicleType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVehicleType) Scan(value interface{}) error {
	if value == nil {
		ns.VehicleType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VehicleType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVehicleType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VehicleType), nil
}

type Follow struct {
	FollowerID  pgtype.UUID        `db:"follower_id" json:"follower_id"`
	FollowingID pgtype.UUID        `db:"following_id" json:"following_id"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type LeaderboardEntry struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	UserID      pgtype.UUID        `db:"user_id" json:"user_id"`
	VehicleType NullVehicleType    `db:"vehicle_type" json:"vehicle_type"`
	PeriodType  string             `db:"period_type" json:"period_type"`
	PeriodStart pgtype.Date        `db:"period_start" json:"period_start"`
	TotalKm     float64            `db:"total_km" json:"total_km"`
	TotalRides  int32              `db:"total_rides" json:"total_rides"`
	Rank        int32              `db:"rank" json:"rank"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Ride struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	UserID          pgtype.UUID        `db:"user_id" json:"user_id"`
	VehicleID       pgtype.UUID        `db:"vehicle_id" json:"vehicle_id"`
	Title           pgtype.Text        `db:"title" json:"title"`
	StartedAt       pgtype.Timestamptz `db:"started_at" json:"started_at"`
	EndedAt         pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	DistanceKm      float64            `db:"distance_km" json:"distance_km"`
	DurationSeconds int32              `db:"duration_seconds" json:"duration_seconds"`
	MaxSpeedKmh     float64            `db:"max_speed_kmh" json:"max_speed_kmh"`
	AvgSpeedKmh     float64            `db:"avg_speed_kmh" json:"avg_speed_kmh"`
	ElevationM      float64            `db:"elevation_m" json:"elevation_m"`
	Calories        int32              `db:"calories" json:"calories"`
	RouteSummary    []byte             `db:"route_summary" json:"route_summary"`
	Status          RideStatus         `db:"status" json:"status"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type RideComment struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	RideID    pgtype.UUID        `db:"ride_id" json:"ride_id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	Content   string             `db:"content" json:"content"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type RideGpsPoint struct {
	ID         int64              `db:"id" json:"id"`
	RideID     pgtype.UUID        `db:"ride_id" json:"ride_id"`
	Latitude   float64            `db:"latitude" json:"latitude"`
	Longitude  float64            `db:"longitude" json:"longitude"`
	SpeedKmh   float64            `db:"speed_kmh" json:"speed_kmh"`
	ElevationM float64            `db:"elevation_m" json:"elevation_m"`
	RecordedAt pgtype.Timestamptz `db:"recorded_at" json:"recorded_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type RideLike struct {
	RideID    pgtype.UUID        `db:"ride_id" json:"ride_id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Username     string             `db:"username" json:"username"`
	Email        string             `db:"email" json:"email"`
	PasswordHash string             `db:"password_hash" json:"password_hash"`
	DisplayName  string             `db:"display_name" json:"display_name"`
	AvatarUrl    pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	PushToken    pgtype.Text        `db:"push_token" json:"push_token"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Vehicle struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	Type      VehicleType        `db:"type" json:"type"`
	Name      string             `db:"name" json:"name"`
	Brand     pgtype.Text        `db:"brand" json:"brand"`
	Color     pgtype.Text        `db:"color" json:"color"`
	IsActive  bool               `db:"is_active" json:"is_active"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
