package sqlc

import "github.com/jackc/pgx/v5/pgxpool"

// Queries provides database query methods
// This is generated from SQL files by sqlc, but we provide a placeholder for Phase 1
type Queries struct {
	db *pgxpool.Pool
}

// New creates a new Queries instance
func New(db *pgxpool.Pool) *Queries {
	return &Queries{db: db}
}

// The actual query methods will be generated by sqlc from internal/db/queries/*.sql files
// when the database schema is ready (Phase 2)
