// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: rides.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const abandonRide = `-- name: AbandonRide :one
UPDATE rides
SET status = 'abandoned', ended_at = NOW(), updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, vehicle_id, title, started_at, ended_at, distance_km, duration_seconds, max_speed_kmh, avg_speed_kmh, elevation_m, calories, route_summary, status, created_at, updated_at
`

type AbandonRideParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) AbandonRide(ctx context.Context, arg AbandonRideParams) (Ride, error) {
	row := q.db.QueryRow(ctx, abandonRide, arg.ID, arg.UserID)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VehicleID,
		&i.Title,
		&i.StartedAt,
		&i.EndedAt,
		&i.DistanceKm,
		&i.DurationSeconds,
		&i.MaxSpeedKmh,
		&i.AvgSpeedKmh,
		&i.ElevationM,
		&i.Calories,
		&i.RouteSummary,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRide = `-- name: CreateRide :one
INSERT INTO rides (user_id, vehicle_id, started_at, status)
VALUES ($1, $2, $3, 'active')
RETURNING id, user_id, vehicle_id, title, started_at, ended_at, distance_km, duration_seconds, max_speed_kmh, avg_speed_kmh, elevation_m, calories, route_summary, status, created_at, updated_at
`

type CreateRideParams struct {
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	VehicleID pgtype.UUID        `db:"vehicle_id" json:"vehicle_id"`
	StartedAt pgtype.Timestamptz `db:"started_at" json:"started_at"`
}

func (q *Queries) CreateRide(ctx context.Context, arg CreateRideParams) (Ride, error) {
	row := q.db.QueryRow(ctx, createRide, arg.UserID, arg.VehicleID, arg.StartedAt)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VehicleID,
		&i.Title,
		&i.StartedAt,
		&i.EndedAt,
		&i.DistanceKm,
		&i.DurationSeconds,
		&i.MaxSpeedKmh,
		&i.AvgSpeedKmh,
		&i.ElevationM,
		&i.Calories,
		&i.RouteSummary,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGPSPointsByRide = `-- name: DeleteGPSPointsByRide :exec
DELETE FROM ride_gps_points
WHERE ride_id = $1
`

func (q *Queries) DeleteGPSPointsByRide(ctx context.Context, rideID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGPSPointsByRide, rideID)
	return err
}

const getActiveRide = `-- name: GetActiveRide :one
SELECT id, user_id, vehicle_id, title, started_at, ended_at, distance_km, duration_seconds, max_speed_kmh, avg_speed_kmh, elevation_m, calories, route_summary, status, created_at, updated_at
FROM rides
WHERE id = $1 AND user_id = $2 AND status = 'active'
`

type GetActiveRideParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetActiveRide(ctx context.Context, arg GetActiveRideParams) (Ride, error) {
	row := q.db.QueryRow(ctx, getActiveRide, arg.ID, arg.UserID)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VehicleID,
		&i.Title,
		&i.StartedAt,
		&i.EndedAt,
		&i.DistanceKm,
		&i.DurationSeconds,
		&i.MaxSpeedKmh,
		&i.AvgSpeedKmh,
		&i.ElevationM,
		&i.Calories,
		&i.RouteSummary,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGPSPointCount = `-- name: GetGPSPointCount :one
SELECT COUNT(*) as count
FROM ride_gps_points
WHERE ride_id = $1
`

func (q *Queries) GetGPSPointCount(ctx context.Context, rideID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getGPSPointCount, rideID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getGPSPointsByRide = `-- name: GetGPSPointsByRide :many
SELECT id, ride_id, latitude, longitude, speed_kmh, elevation_m, recorded_at, created_at
FROM ride_gps_points
WHERE ride_id = $1
ORDER BY recorded_at ASC
`

func (q *Queries) GetGPSPointsByRide(ctx context.Context, rideID pgtype.UUID) ([]RideGpsPoint, error) {
	rows, err := q.db.Query(ctx, getGPSPointsByRide, rideID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RideGpsPoint{}
	for rows.Next() {
		var i RideGpsPoint
		if err := rows.Scan(
			&i.ID,
			&i.RideID,
			&i.Latitude,
			&i.Longitude,
			&i.SpeedKmh,
			&i.ElevationM,
			&i.RecordedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRideByID = `-- name: GetRideByID :one
SELECT id, user_id, vehicle_id, title, started_at, ended_at, distance_km, duration_seconds, max_speed_kmh, avg_speed_kmh, elevation_m, calories, route_summary, status, created_at, updated_at
FROM rides
WHERE id = $1
`

func (q *Queries) GetRideByID(ctx context.Context, id pgtype.UUID) (Ride, error) {
	row := q.db.QueryRow(ctx, getRideByID, id)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VehicleID,
		&i.Title,
		&i.StartedAt,
		&i.EndedAt,
		&i.DistanceKm,
		&i.DurationSeconds,
		&i.MaxSpeedKmh,
		&i.AvgSpeedKmh,
		&i.ElevationM,
		&i.Calories,
		&i.RouteSummary,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRideCount = `-- name: GetRideCount :one
SELECT COUNT(*) as count
FROM rides
WHERE user_id = $1 AND status = 'completed'
`

func (q *Queries) GetRideCount(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getRideCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRideForUpdate = `-- name: GetRideForUpdate :one
SELECT id, user_id, vehicle_id, title, started_at, ended_at, distance_km, duration_seconds, max_speed_kmh, avg_speed_kmh, elevation_m, calories, route_summary, status, created_at, updated_at
FROM rides
WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetRideForUpdate(ctx context.Context, id pgtype.UUID) (Ride, error) {
	row := q.db.QueryRow(ctx, getRideForUpdate, id)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VehicleID,
		&i.Title,
		&i.StartedAt,
		&i.EndedAt,
		&i.DistanceKm,
		&i.DurationSeconds,
		&i.MaxSpeedKmh,
		&i.AvgSpeedKmh,
		&i.ElevationM,
		&i.Calories,
		&i.RouteSummary,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserRideStats = `-- name: GetUserRideStats :one
SELECT
    COUNT(*) as total_rides,
    COALESCE(SUM(distance_km), 0) as total_distance_km,
    COALESCE(SUM(calories), 0) as total_calories,
    COALESCE(SUM(elevation_m), 0) as total_elevation_m,
    COALESCE(SUM(EXTRACT(EPOCH FROM (ended_at - started_at))), 0)::INT as total_seconds
FROM rides
WHERE user_id = $1 AND status = 'completed'
`

type GetUserRideStatsRow struct {
	TotalRides      int64       `db:"total_rides" json:"total_rides"`
	TotalDistanceKm interface{} `db:"total_distance_km" json:"total_distance_km"`
	TotalCalories   interface{} `db:"total_calories" json:"total_calories"`
	TotalElevationM interface{} `db:"total_elevation_m" json:"total_elevation_m"`
	TotalSeconds    int32       `db:"total_seconds" json:"total_seconds"`
}

func (q *Queries) GetUserRideStats(ctx context.Context, userID pgtype.UUID) (GetUserRideStatsRow, error) {
	row := q.db.QueryRow(ctx, getUserRideStats, userID)
	var i GetUserRideStatsRow
	err := row.Scan(
		&i.TotalRides,
		&i.TotalDistanceKm,
		&i.TotalCalories,
		&i.TotalElevationM,
		&i.TotalSeconds,
	)
	return i, err
}

const insertGPSPoint = `-- name: InsertGPSPoint :exec

INSERT INTO ride_gps_points (ride_id, latitude, longitude, speed_kmh, elevation_m, recorded_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertGPSPointParams struct {
	RideID     pgtype.UUID        `db:"ride_id" json:"ride_id"`
	Latitude   float64            `db:"latitude" json:"latitude"`
	Longitude  float64            `db:"longitude" json:"longitude"`
	SpeedKmh   float64            `db:"speed_kmh" json:"speed_kmh"`
	ElevationM float64            `db:"elevation_m" json:"elevation_m"`
	RecordedAt pgtype.Timestamptz `db:"recorded_at" json:"recorded_at"`
}

// GPS Points Queries
func (q *Queries) InsertGPSPoint(ctx context.Context, arg InsertGPSPointParams) error {
	_, err := q.db.Exec(ctx, insertGPSPoint,
		arg.RideID,
		arg.Latitude,
		arg.Longitude,
		arg.SpeedKmh,
		arg.ElevationM,
		arg.RecordedAt,
	)
	return err
}

const insertGPSPointsBatch = `-- name: InsertGPSPointsBatch :exec
INSERT INTO ride_gps_points (ride_id, latitude, longitude, speed_kmh, elevation_m, recorded_at)
SELECT
    UNNEST($1::uuid[]) as ride_id,
    UNNEST($2::float8[]) as latitude,
    UNNEST($3::float8[]) as longitude,
    UNNEST($4::float8[]) as speed_kmh,
    UNNEST($5::float8[]) as elevation_m,
    UNNEST($6::timestamptz[]) as recorded_at
`

type InsertGPSPointsBatchParams struct {
	RideIds     []pgtype.UUID        `db:"ride_ids" json:"ride_ids"`
	Latitudes   []float64            `db:"latitudes" json:"latitudes"`
	Longitudes  []float64            `db:"longitudes" json:"longitudes"`
	Speeds      []float64            `db:"speeds" json:"speeds"`
	Elevations  []float64            `db:"elevations" json:"elevations"`
	RecordedAts []pgtype.Timestamptz `db:"recorded_ats" json:"recorded_ats"`
}

func (q *Queries) InsertGPSPointsBatch(ctx context.Context, arg InsertGPSPointsBatchParams) error {
	_, err := q.db.Exec(ctx, insertGPSPointsBatch,
		arg.RideIds,
		arg.Latitudes,
		arg.Longitudes,
		arg.Speeds,
		arg.Elevations,
		arg.RecordedAts,
	)
	return err
}

const listRidesByUser = `-- name: ListRidesByUser :many
SELECT id, user_id, vehicle_id, title, started_at, ended_at, distance_km, duration_seconds, max_speed_kmh, avg_speed_kmh, elevation_m, calories, route_summary, status, created_at, updated_at
FROM rides
WHERE user_id = $1 AND status = 'completed'
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type ListRidesByUserParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListRidesByUser(ctx context.Context, arg ListRidesByUserParams) ([]Ride, error) {
	rows, err := q.db.Query(ctx, listRidesByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ride{}
	for rows.Next() {
		var i Ride
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VehicleID,
			&i.Title,
			&i.StartedAt,
			&i.EndedAt,
			&i.DistanceKm,
			&i.DurationSeconds,
			&i.MaxSpeedKmh,
			&i.AvgSpeedKmh,
			&i.ElevationM,
			&i.Calories,
			&i.RouteSummary,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRidesByUserAndVehicle = `-- name: ListRidesByUserAndVehicle :many
SELECT id, user_id, vehicle_id, title, started_at, ended_at, distance_km, duration_seconds, max_speed_kmh, avg_speed_kmh, elevation_m, calories, route_summary, status, created_at, updated_at
FROM rides
WHERE user_id = $1 AND vehicle_id = $2 AND status = 'completed'
ORDER BY started_at DESC
LIMIT $3 OFFSET $4
`

type ListRidesByUserAndVehicleParams struct {
	UserID    pgtype.UUID `db:"user_id" json:"user_id"`
	VehicleID pgtype.UUID `db:"vehicle_id" json:"vehicle_id"`
	Limit     int32       `db:"limit" json:"limit"`
	Offset    int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListRidesByUserAndVehicle(ctx context.Context, arg ListRidesByUserAndVehicleParams) ([]Ride, error) {
	rows, err := q.db.Query(ctx, listRidesByUserAndVehicle,
		arg.UserID,
		arg.VehicleID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ride{}
	for rows.Next() {
		var i Ride
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VehicleID,
			&i.Title,
			&i.StartedAt,
			&i.EndedAt,
			&i.DistanceKm,
			&i.DurationSeconds,
			&i.MaxSpeedKmh,
			&i.AvgSpeedKmh,
			&i.ElevationM,
			&i.Calories,
			&i.RouteSummary,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRideCompleted = `-- name: UpdateRideCompleted :one
UPDATE rides
SET ended_at = $2,
    status = 'completed',
    distance_km = $3,
    duration_seconds = $4,
    max_speed_kmh = $5,
    avg_speed_kmh = $6,
    elevation_m = $7,
    calories = $8,
    route_summary = $9,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, vehicle_id, title, started_at, ended_at, distance_km, duration_seconds, max_speed_kmh, avg_speed_kmh, elevation_m, calories, route_summary, status, created_at, updated_at
`

type UpdateRideCompletedParams struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	EndedAt         pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	DistanceKm      float64            `db:"distance_km" json:"distance_km"`
	DurationSeconds int32              `db:"duration_seconds" json:"duration_seconds"`
	MaxSpeedKmh     float64            `db:"max_speed_kmh" json:"max_speed_kmh"`
	AvgSpeedKmh     float64            `db:"avg_speed_kmh" json:"avg_speed_kmh"`
	ElevationM      float64            `db:"elevation_m" json:"elevation_m"`
	Calories        int32              `db:"calories" json:"calories"`
	RouteSummary    []byte             `db:"route_summary" json:"route_summary"`
}

func (q *Queries) UpdateRideCompleted(ctx context.Context, arg UpdateRideCompletedParams) (Ride, error) {
	row := q.db.QueryRow(ctx, updateRideCompleted,
		arg.ID,
		arg.EndedAt,
		arg.DistanceKm,
		arg.DurationSeconds,
		arg.MaxSpeedKmh,
		arg.AvgSpeedKmh,
		arg.ElevationM,
		arg.Calories,
		arg.RouteSummary,
	)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VehicleID,
		&i.Title,
		&i.StartedAt,
		&i.EndedAt,
		&i.DistanceKm,
		&i.DurationSeconds,
		&i.MaxSpeedKmh,
		&i.AvgSpeedKmh,
		&i.ElevationM,
		&i.Calories,
		&i.RouteSummary,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
