// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: social.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :one

INSERT INTO ride_comments (ride_id, user_id, content)
VALUES ($1, $2, $3)
RETURNING id, ride_id, user_id, content, created_at, updated_at
`

type CreateCommentParams struct {
	RideID  pgtype.UUID `db:"ride_id" json:"ride_id"`
	UserID  pgtype.UUID `db:"user_id" json:"user_id"`
	Content string      `db:"content" json:"content"`
}

// Comments Queries
func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (RideComment, error) {
	row := q.db.QueryRow(ctx, createComment, arg.RideID, arg.UserID, arg.Content)
	var i RideComment
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM ride_comments
WHERE id = $1 AND user_id = $2
`

type DeleteCommentParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteComment(ctx context.Context, arg DeleteCommentParams) error {
	_, err := q.db.Exec(ctx, deleteComment, arg.ID, arg.UserID)
	return err
}

const followUser = `-- name: FollowUser :exec

INSERT INTO follows (follower_id, following_id)
VALUES ($1, $2)
ON CONFLICT (follower_id, following_id) DO NOTHING
`

type FollowUserParams struct {
	FollowerID  pgtype.UUID `db:"follower_id" json:"follower_id"`
	FollowingID pgtype.UUID `db:"following_id" json:"following_id"`
}

// Follows Queries
func (q *Queries) FollowUser(ctx context.Context, arg FollowUserParams) error {
	_, err := q.db.Exec(ctx, followUser, arg.FollowerID, arg.FollowingID)
	return err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, ride_id, user_id, content, created_at, updated_at
FROM ride_comments
WHERE id = $1
`

func (q *Queries) GetCommentByID(ctx context.Context, id pgtype.UUID) (RideComment, error) {
	row := q.db.QueryRow(ctx, getCommentByID, id)
	var i RideComment
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFollowerCount = `-- name: GetFollowerCount :one
SELECT COUNT(*) as count
FROM follows
WHERE following_id = $1
`

func (q *Queries) GetFollowerCount(ctx context.Context, followingID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getFollowerCount, followingID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getFollowingCount = `-- name: GetFollowingCount :one
SELECT COUNT(*) as count
FROM follows
WHERE follower_id = $1
`

func (q *Queries) GetFollowingCount(ctx context.Context, followerID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getFollowingCount, followerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getFollowingFeed = `-- name: GetFollowingFeed :many

SELECT
    r.id, r.user_id, r.vehicle_id, r.title, r.started_at, r.ended_at,
    r.distance_km, r.duration_seconds, r.max_speed_kmh, r.avg_speed_kmh,
    r.elevation_m, r.calories, r.route_summary, r.status,
    r.created_at, r.updated_at,
    u.username, u.display_name, u.avatar_url,
    v.type as vehicle_type, v.name as vehicle_name,
    COALESCE(COUNT(DISTINCT rl.user_id), 0) as like_count,
    COALESCE(COUNT(DISTINCT rc.id), 0) as comment_count
FROM rides r
JOIN users u ON r.user_id = u.id
JOIN vehicles v ON r.vehicle_id = v.id
LEFT JOIN ride_likes rl ON r.id = rl.ride_id
LEFT JOIN ride_comments rc ON r.id = rc.ride_id
WHERE r.status = 'completed' AND EXISTS(
    SELECT 1 FROM follows WHERE follower_id = $1 AND following_id = r.user_id
)
GROUP BY r.id, u.id, v.id
ORDER BY r.started_at DESC
LIMIT $2 OFFSET $3
`

type GetFollowingFeedParams struct {
	FollowerID pgtype.UUID `db:"follower_id" json:"follower_id"`
	Limit      int32       `db:"limit" json:"limit"`
	Offset     int32       `db:"offset" json:"offset"`
}

type GetFollowingFeedRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	UserID          pgtype.UUID        `db:"user_id" json:"user_id"`
	VehicleID       pgtype.UUID        `db:"vehicle_id" json:"vehicle_id"`
	Title           pgtype.Text        `db:"title" json:"title"`
	StartedAt       pgtype.Timestamptz `db:"started_at" json:"started_at"`
	EndedAt         pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	DistanceKm      float64            `db:"distance_km" json:"distance_km"`
	DurationSeconds int32              `db:"duration_seconds" json:"duration_seconds"`
	MaxSpeedKmh     float64            `db:"max_speed_kmh" json:"max_speed_kmh"`
	AvgSpeedKmh     float64            `db:"avg_speed_kmh" json:"avg_speed_kmh"`
	ElevationM      float64            `db:"elevation_m" json:"elevation_m"`
	Calories        int32              `db:"calories" json:"calories"`
	RouteSummary    []byte             `db:"route_summary" json:"route_summary"`
	Status          RideStatus         `db:"status" json:"status"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Username        string             `db:"username" json:"username"`
	DisplayName     string             `db:"display_name" json:"display_name"`
	AvatarUrl       pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	VehicleType     VehicleType        `db:"vehicle_type" json:"vehicle_type"`
	VehicleName     string             `db:"vehicle_name" json:"vehicle_name"`
	LikeCount       interface{}        `db:"like_count" json:"like_count"`
	CommentCount    interface{}        `db:"comment_count" json:"comment_count"`
}

// Feed Query (recent rides from followed users)
func (q *Queries) GetFollowingFeed(ctx context.Context, arg GetFollowingFeedParams) ([]GetFollowingFeedRow, error) {
	rows, err := q.db.Query(ctx, getFollowingFeed, arg.FollowerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFollowingFeedRow{}
	for rows.Next() {
		var i GetFollowingFeedRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VehicleID,
			&i.Title,
			&i.StartedAt,
			&i.EndedAt,
			&i.DistanceKm,
			&i.DurationSeconds,
			&i.MaxSpeedKmh,
			&i.AvgSpeedKmh,
			&i.ElevationM,
			&i.Calories,
			&i.RouteSummary,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.VehicleType,
			&i.VehicleName,
			&i.LikeCount,
			&i.CommentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowingFeedWithUserStatus = `-- name: GetFollowingFeedWithUserStatus :many

SELECT
    r.id, r.user_id, r.vehicle_id, r.title, r.started_at, r.ended_at,
    r.distance_km, r.duration_seconds, r.max_speed_kmh, r.avg_speed_kmh,
    r.elevation_m, r.calories, r.route_summary, r.status,
    r.created_at, r.updated_at,
    u.username, u.display_name, u.avatar_url,
    v.type as vehicle_type, v.name as vehicle_name,
    COALESCE(COUNT(DISTINCT rl.user_id), 0) as like_count,
    COALESCE(COUNT(DISTINCT rc.id), 0) as comment_count,
    EXISTS(SELECT 1 FROM ride_likes WHERE ride_id = r.id AND ride_likes.user_id = $1) as user_has_liked
FROM rides r
JOIN users u ON r.user_id = u.id
JOIN vehicles v ON r.vehicle_id = v.id
LEFT JOIN ride_likes rl ON r.id = rl.ride_id
LEFT JOIN ride_comments rc ON r.id = rc.ride_id
WHERE r.status = 'completed' AND EXISTS(
    SELECT 1 FROM follows WHERE follower_id = $1 AND following_id = r.user_id
)
GROUP BY r.id, u.id, v.id
ORDER BY r.started_at DESC
LIMIT $2 OFFSET $3
`

type GetFollowingFeedWithUserStatusParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
}

type GetFollowingFeedWithUserStatusRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	UserID          pgtype.UUID        `db:"user_id" json:"user_id"`
	VehicleID       pgtype.UUID        `db:"vehicle_id" json:"vehicle_id"`
	Title           pgtype.Text        `db:"title" json:"title"`
	StartedAt       pgtype.Timestamptz `db:"started_at" json:"started_at"`
	EndedAt         pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	DistanceKm      float64            `db:"distance_km" json:"distance_km"`
	DurationSeconds int32              `db:"duration_seconds" json:"duration_seconds"`
	MaxSpeedKmh     float64            `db:"max_speed_kmh" json:"max_speed_kmh"`
	AvgSpeedKmh     float64            `db:"avg_speed_kmh" json:"avg_speed_kmh"`
	ElevationM      float64            `db:"elevation_m" json:"elevation_m"`
	Calories        int32              `db:"calories" json:"calories"`
	RouteSummary    []byte             `db:"route_summary" json:"route_summary"`
	Status          RideStatus         `db:"status" json:"status"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Username        string             `db:"username" json:"username"`
	DisplayName     string             `db:"display_name" json:"display_name"`
	AvatarUrl       pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	VehicleType     VehicleType        `db:"vehicle_type" json:"vehicle_type"`
	VehicleName     string             `db:"vehicle_name" json:"vehicle_name"`
	LikeCount       interface{}        `db:"like_count" json:"like_count"`
	CommentCount    interface{}        `db:"comment_count" json:"comment_count"`
	UserHasLiked    bool               `db:"user_has_liked" json:"user_has_liked"`
}

// Get feed with user's like status
func (q *Queries) GetFollowingFeedWithUserStatus(ctx context.Context, arg GetFollowingFeedWithUserStatusParams) ([]GetFollowingFeedWithUserStatusRow, error) {
	rows, err := q.db.Query(ctx, getFollowingFeedWithUserStatus, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFollowingFeedWithUserStatusRow{}
	for rows.Next() {
		var i GetFollowingFeedWithUserStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VehicleID,
			&i.Title,
			&i.StartedAt,
			&i.EndedAt,
			&i.DistanceKm,
			&i.DurationSeconds,
			&i.MaxSpeedKmh,
			&i.AvgSpeedKmh,
			&i.ElevationM,
			&i.Calories,
			&i.RouteSummary,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.VehicleType,
			&i.VehicleName,
			&i.LikeCount,
			&i.CommentCount,
			&i.UserHasLiked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRideCommentCount = `-- name: GetRideCommentCount :one
SELECT COUNT(*) as count
FROM ride_comments
WHERE ride_id = $1
`

func (q *Queries) GetRideCommentCount(ctx context.Context, rideID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getRideCommentCount, rideID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRideLikeCount = `-- name: GetRideLikeCount :one
SELECT COUNT(*) as count
FROM ride_likes
WHERE ride_id = $1
`

func (q *Queries) GetRideLikeCount(ctx context.Context, rideID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getRideLikeCount, rideID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const hasUserLikedRide = `-- name: HasUserLikedRide :one
SELECT EXISTS(SELECT 1 FROM ride_likes WHERE ride_id = $1 AND user_id = $2) as has_liked
`

type HasUserLikedRideParams struct {
	RideID pgtype.UUID `db:"ride_id" json:"ride_id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) HasUserLikedRide(ctx context.Context, arg HasUserLikedRideParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasUserLikedRide, arg.RideID, arg.UserID)
	var has_liked bool
	err := row.Scan(&has_liked)
	return has_liked, err
}

const isFollowing = `-- name: IsFollowing :one
SELECT EXISTS(SELECT 1 FROM follows WHERE follower_id = $1 AND following_id = $2) as is_following
`

type IsFollowingParams struct {
	FollowerID  pgtype.UUID `db:"follower_id" json:"follower_id"`
	FollowingID pgtype.UUID `db:"following_id" json:"following_id"`
}

func (q *Queries) IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFollowing, arg.FollowerID, arg.FollowingID)
	var is_following bool
	err := row.Scan(&is_following)
	return is_following, err
}

const likeRide = `-- name: LikeRide :exec

INSERT INTO ride_likes (ride_id, user_id)
VALUES ($1, $2)
ON CONFLICT (ride_id, user_id) DO NOTHING
`

type LikeRideParams struct {
	RideID pgtype.UUID `db:"ride_id" json:"ride_id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

// Likes Queries
func (q *Queries) LikeRide(ctx context.Context, arg LikeRideParams) error {
	_, err := q.db.Exec(ctx, likeRide, arg.RideID, arg.UserID)
	return err
}

const listFollowers = `-- name: ListFollowers :many
SELECT u.id, u.username, u.display_name, u.avatar_url
FROM follows f
JOIN users u ON f.follower_id = u.id
WHERE f.following_id = $1
ORDER BY f.created_at DESC
LIMIT $2 OFFSET $3
`

type ListFollowersParams struct {
	FollowingID pgtype.UUID `db:"following_id" json:"following_id"`
	Limit       int32       `db:"limit" json:"limit"`
	Offset      int32       `db:"offset" json:"offset"`
}

type ListFollowersRow struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	Username    string      `db:"username" json:"username"`
	DisplayName string      `db:"display_name" json:"display_name"`
	AvatarUrl   pgtype.Text `db:"avatar_url" json:"avatar_url"`
}

func (q *Queries) ListFollowers(ctx context.Context, arg ListFollowersParams) ([]ListFollowersRow, error) {
	rows, err := q.db.Query(ctx, listFollowers, arg.FollowingID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFollowersRow{}
	for rows.Next() {
		var i ListFollowersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowing = `-- name: ListFollowing :many
SELECT u.id, u.username, u.display_name, u.avatar_url
FROM follows f
JOIN users u ON f.following_id = u.id
WHERE f.follower_id = $1
ORDER BY f.created_at DESC
LIMIT $2 OFFSET $3
`

type ListFollowingParams struct {
	FollowerID pgtype.UUID `db:"follower_id" json:"follower_id"`
	Limit      int32       `db:"limit" json:"limit"`
	Offset     int32       `db:"offset" json:"offset"`
}

type ListFollowingRow struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	Username    string      `db:"username" json:"username"`
	DisplayName string      `db:"display_name" json:"display_name"`
	AvatarUrl   pgtype.Text `db:"avatar_url" json:"avatar_url"`
}

func (q *Queries) ListFollowing(ctx context.Context, arg ListFollowingParams) ([]ListFollowingRow, error) {
	rows, err := q.db.Query(ctx, listFollowing, arg.FollowerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFollowingRow{}
	for rows.Next() {
		var i ListFollowingRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRideComments = `-- name: ListRideComments :many
SELECT id, ride_id, user_id, content, created_at, updated_at
FROM ride_comments
WHERE ride_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListRideCommentsParams struct {
	RideID pgtype.UUID `db:"ride_id" json:"ride_id"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListRideComments(ctx context.Context, arg ListRideCommentsParams) ([]RideComment, error) {
	rows, err := q.db.Query(ctx, listRideComments, arg.RideID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RideComment{}
	for rows.Next() {
		var i RideComment
		if err := rows.Scan(
			&i.ID,
			&i.RideID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unfollowUser = `-- name: UnfollowUser :exec
DELETE FROM follows
WHERE follower_id = $1 AND following_id = $2
`

type UnfollowUserParams struct {
	FollowerID  pgtype.UUID `db:"follower_id" json:"follower_id"`
	FollowingID pgtype.UUID `db:"following_id" json:"following_id"`
}

func (q *Queries) UnfollowUser(ctx context.Context, arg UnfollowUserParams) error {
	_, err := q.db.Exec(ctx, unfollowUser, arg.FollowerID, arg.FollowingID)
	return err
}

const unlikeRide = `-- name: UnlikeRide :exec
DELETE FROM ride_likes
WHERE ride_id = $1 AND user_id = $2
`

type UnlikeRideParams struct {
	RideID pgtype.UUID `db:"ride_id" json:"ride_id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) UnlikeRide(ctx context.Context, arg UnlikeRideParams) error {
	_, err := q.db.Exec(ctx, unlikeRide, arg.RideID, arg.UserID)
	return err
}

const updateComment = `-- name: UpdateComment :one
UPDATE ride_comments
SET content = $2, updated_at = NOW()
WHERE id = $1 AND user_id = $3
RETURNING id, ride_id, user_id, content, created_at, updated_at
`

type UpdateCommentParams struct {
	ID      pgtype.UUID `db:"id" json:"id"`
	Content string      `db:"content" json:"content"`
	UserID  pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (RideComment, error) {
	row := q.db.QueryRow(ctx, updateComment, arg.ID, arg.Content, arg.UserID)
	var i RideComment
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
