// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: vehicles.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVehicle = `-- name: CreateVehicle :one
INSERT INTO vehicles (user_id, type, name, brand, color)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, type, name, brand, color, is_active, created_at, updated_at
`

type CreateVehicleParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Type   VehicleType `db:"type" json:"type"`
	Name   string      `db:"name" json:"name"`
	Brand  pgtype.Text `db:"brand" json:"brand"`
	Color  pgtype.Text `db:"color" json:"color"`
}

func (q *Queries) CreateVehicle(ctx context.Context, arg CreateVehicleParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, createVehicle,
		arg.UserID,
		arg.Type,
		arg.Name,
		arg.Brand,
		arg.Color,
	)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.Brand,
		&i.Color,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateVehicle = `-- name: DeactivateVehicle :exec
UPDATE vehicles
SET is_active = FALSE, updated_at = NOW()
WHERE id = $1 AND user_id = $2
`

type DeactivateVehicleParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeactivateVehicle(ctx context.Context, arg DeactivateVehicleParams) error {
	_, err := q.db.Exec(ctx, deactivateVehicle, arg.ID, arg.UserID)
	return err
}

const deleteVehicle = `-- name: DeleteVehicle :execrows
DELETE FROM vehicles v
WHERE v.id = $1 AND v.user_id = $2
AND NOT EXISTS (
    SELECT 1 FROM rides WHERE rides.vehicle_id = v.id AND rides.status = 'active'
)
`

type DeleteVehicleParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteVehicle(ctx context.Context, arg DeleteVehicleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteVehicle, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getVehicleByID = `-- name: GetVehicleByID :one
SELECT id, user_id, type, name, brand, color, is_active, created_at, updated_at
FROM vehicles
WHERE id = $1
`

func (q *Queries) GetVehicleByID(ctx context.Context, id pgtype.UUID) (Vehicle, error) {
	row := q.db.QueryRow(ctx, getVehicleByID, id)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.Brand,
		&i.Color,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVehicleByIDAndUser = `-- name: GetVehicleByIDAndUser :one
SELECT id, user_id, type, name, brand, color, is_active, created_at, updated_at
FROM vehicles
WHERE id = $1 AND user_id = $2
`

type GetVehicleByIDAndUserParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetVehicleByIDAndUser(ctx context.Context, arg GetVehicleByIDAndUserParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, getVehicleByIDAndUser, arg.ID, arg.UserID)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.Brand,
		&i.Color,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasActiveRide = `-- name: HasActiveRide :one
SELECT EXISTS(
    SELECT 1 FROM rides
    WHERE vehicle_id = $1 AND status = 'active'
) as has_active_ride
`

func (q *Queries) HasActiveRide(ctx context.Context, vehicleID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveRide, vehicleID)
	var has_active_ride bool
	err := row.Scan(&has_active_ride)
	return has_active_ride, err
}

const listActiveVehiclesByUser = `-- name: ListActiveVehiclesByUser :many
SELECT id, user_id, type, name, brand, color, is_active, created_at, updated_at
FROM vehicles
WHERE user_id = $1 AND is_active = TRUE
ORDER BY created_at DESC
`

func (q *Queries) ListActiveVehiclesByUser(ctx context.Context, userID pgtype.UUID) ([]Vehicle, error) {
	rows, err := q.db.Query(ctx, listActiveVehiclesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vehicle{}
	for rows.Next() {
		var i Vehicle
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Name,
			&i.Brand,
			&i.Color,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehiclesByUser = `-- name: ListVehiclesByUser :many
SELECT id, user_id, type, name, brand, color, is_active, created_at, updated_at
FROM vehicles
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListVehiclesByUser(ctx context.Context, userID pgtype.UUID) ([]Vehicle, error) {
	rows, err := q.db.Query(ctx, listVehiclesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vehicle{}
	for rows.Next() {
		var i Vehicle
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Name,
			&i.Brand,
			&i.Color,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVehicle = `-- name: UpdateVehicle :one
UPDATE vehicles
SET type = $3,
    name = $4,
    brand = $5,
    color = $6,
    updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, type, name, brand, color, is_active, created_at, updated_at
`

type UpdateVehicleParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Type   VehicleType `db:"type" json:"type"`
	Name   string      `db:"name" json:"name"`
	Brand  pgtype.Text `db:"brand" json:"brand"`
	Color  pgtype.Text `db:"color" json:"color"`
}

func (q *Queries) UpdateVehicle(ctx context.Context, arg UpdateVehicleParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, updateVehicle,
		arg.ID,
		arg.UserID,
		arg.Type,
		arg.Name,
		arg.Brand,
		arg.Color,
	)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.Brand,
		&i.Color,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
