// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vehicles.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVehicle = `-- name: CreateVehicle :one
INSERT INTO vehicles (user_id, type, name, brand, color)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, type, name, brand, color, is_active, created_at, updated_at
`

type CreateVehicleParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Type   VehicleType `db:"type" json:"type"`
	Name   string      `db:"name" json:"name"`
	Brand  pgtype.Text `db:"brand" json:"brand"`
	Color  pgtype.Text `db:"color" json:"color"`
}

func (q *Queries) CreateVehicle(ctx context.Context, arg CreateVehicleParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, createVehicle,
		arg.UserID,
		arg.Type,
		arg.Name,
		arg.Brand,
		arg.Color,
	)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.Brand,
		&i.Color,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateVehicle = `-- name: DeactivateVehicle :exec
UPDATE vehicles
SET is_active = FALSE, updated_at = NOW()
WHERE id = $1 AND user_id = $2
`

type DeactivateVehicleParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeactivateVehicle(ctx context.Context, arg DeactivateVehicleParams) error {
	_, err := q.db.Exec(ctx, deactivateVehicle, arg.ID, arg.UserID)
	return err
}

const deleteVehicle = `-- name: DeleteVehicle :exec
DELETE FROM vehicles
WHERE id = $1 AND user_id = $2
`

type DeleteVehicleParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteVehicle(ctx context.Context, arg DeleteVehicleParams) error {
	_, err := q.db.Exec(ctx, deleteVehicle, arg.ID, arg.UserID)
	return err
}

const getVehicleByID = `-- name: GetVehicleByID :one
SELECT id, user_id, type, name, brand, color, is_active, created_at, updated_at
FROM vehicles
WHERE id = $1
`

func (q *Queries) GetVehicleByID(ctx context.Context, id pgtype.UUID) (Vehicle, error) {
	row := q.db.QueryRow(ctx, getVehicleByID, id)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.Brand,
		&i.Color,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveVehiclesByUser = `-- name: ListActiveVehiclesByUser :many
SELECT id, user_id, type, name, brand, color, is_active, created_at, updated_at
FROM vehicles
WHERE user_id = $1 AND is_active = TRUE
ORDER BY created_at DESC
`

func (q *Queries) ListActiveVehiclesByUser(ctx context.Context, userID pgtype.UUID) ([]Vehicle, error) {
	rows, err := q.db.Query(ctx, listActiveVehiclesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vehicle{}
	for rows.Next() {
		var i Vehicle
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Name,
			&i.Brand,
			&i.Color,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehiclesByUser = `-- name: ListVehiclesByUser :many
SELECT id, user_id, type, name, brand, color, is_active, created_at, updated_at
FROM vehicles
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListVehiclesByUser(ctx context.Context, userID pgtype.UUID) ([]Vehicle, error) {
	rows, err := q.db.Query(ctx, listVehiclesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vehicle{}
	for rows.Next() {
		var i Vehicle
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Name,
			&i.Brand,
			&i.Color,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVehicle = `-- name: UpdateVehicle :one
UPDATE vehicles
SET type = COALESCE($3, type),
    name = COALESCE($4, name),
    brand = COALESCE($5, brand),
    color = COALESCE($6, color),
    updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, type, name, brand, color, is_active, created_at, updated_at
`

type UpdateVehicleParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Type   VehicleType `db:"type" json:"type"`
	Name   string      `db:"name" json:"name"`
	Brand  pgtype.Text `db:"brand" json:"brand"`
	Color  pgtype.Text `db:"color" json:"color"`
}

func (q *Queries) UpdateVehicle(ctx context.Context, arg UpdateVehicleParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, updateVehicle,
		arg.ID,
		arg.UserID,
		arg.Type,
		arg.Name,
		arg.Brand,
		arg.Color,
	)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.Brand,
		&i.Color,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
