package db

// Queries defines the database query interface for handlers and services.
// In Phase 2, this will be satisfied by code generated from sqlc.
// For Phase 1, this is a placeholder that defines what methods will be available.
type Queries interface {
	// Placeholder - actual methods will be generated by sqlc in Phase 2
	// Example generated methods will include:
	// CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	// GetRideByID(ctx context.Context, id uuid.UUID) (Ride, error)
	// ... etc
}
