package db

// Queries defines the database query interface for handlers and services.
// In Phase 2, this will be satisfied by code generated from sqlc.
// For Phase 1, this is a placeholder that defines what methods will be available.
type Queries interface {
	// Placeholder - actual methods will be generated by sqlc in Phase 2
	// Example generated methods will include:
	// CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	// GetRideByID(ctx context.Context, id uuid.UUID) (Ride, error)
	// ... etc
}

// NewQueries creates a new Queries instance.
// In Phase 2, this will return a properly generated sqlc.Queries instance.
func NewQueries() Queries {
	// Phase 1: return nil placeholder
	// Phase 2: return sqlc.New(db)
	return nil
}
